apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express-db
  template:
    metadata:
      labels:
        app: mongo-express-db
    spec:
      containers:
      - name: mongo-express-db
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_INITDB_ROOT_USERNAME
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret
                key: MONGO_INITDB_ROOT_PASSWORD     
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-db-configmap
                key: database_url


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express-db-external-service
spec:
  selector:
    app: mongo-express-db
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30005